### ISSUE TITLE
Would you like to join my organization?

### ISSUE THREAD

**Issue by ghost** [lyushher/lyushher#3]
I was looking over your portfolio and it seems very good!

I would like to have you join 1 organization of mine, it would help a lot. Simple [RPly](https://rply.readthedocs.io/en/latest/) and [Python](https://python.org) experience is required.

In my organization, @ProjectBML, I am currently building a markup language that compiles to HTML! Don't worry, most of it is  done, I just want a couple ideas put in from you.

Feel free to decline or delete this issue, no other friends of mine would probably like to try this.

Thanks,  
acaiberii

**Comment by lyushher** [comment]
Hello, thank you for your offer!

I'd love to join your organization and help you continue your project together, but I don't know much about HTML.
If you want my help on just [RPly](https://rply.readthedocs.io/en/latest/) and [Python](https://www.python.org), I can help you.

Let's continue the text via email, please.

**Comment by ghost** [comment]
Thank you, my email is ```AcaiBerii@protonmail.com```
